services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    disk:
      name: mydisc
      mountPath: /var/data
      sizeGB: 5
    envVars:
      - key: NODE_VERSION
        value: 16.13.0
      - key: NODE_ENV
        value: production
      - key: postgres://wagnerdev:DXpMHfs0CdEUcSgxTCTY6zJ0OeryUwbA@dpg-c8lspur97ej210c4ducg/newiedb
        fromDatabase:
          name: newiedb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true

databases:
  - name: newiedb
    plan: starter
