services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    disk:
      name: mydisc
      mountPath: /var/data
      sizeGB: 5
    envVars:
      - key: NODE_VERSION
        value: 16.13.0
      - key: NODE_ENV
        value: production
      - key: postgres://strapi_c2mz_user:hIE1G8GX8TnoRmomBxxloJx6OyRgYSjB@dpg-c7fbavd0mal5kjhprp2g/strapi_c2mz
        fromDatabase:
          name: strapi_c2mz
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true

databases:
  - name: strapi-c2mz
    plan: starter
